development:
  database: gemcamp_norman
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: gemcamp_norman_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db